# Generated by Django 5.1.4 on 2025-02-05 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_tools', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'day'], name='productivit_user_id_fcfb0f_idx'),
        ),
    ]
